// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class ChiTietPhieuXuat
{
    public int MaChiTietXuat { get; set; }

    public decimal GiaTien { get; set; }

    public int MaPhieuXuat { get; set; }

    public int MaSeri { get; set; }

    public virtual PhieuXuat MaPhieuXuatNavigation { get; set; }

    public virtual SeriSanPham MaSeriNavigation { get; set; }
}