// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class ChiTietPhieuNhap
{
    public int MaChiTietNhap { get; set; }

    public int SoLuong { get; set; }

    public decimal DonGiaNhap { get; set; }

    public int MaPhieuNhap { get; set; }

    public int MaSanPham { get; set; }

    public virtual PhieuNhap MaPhieuNhapNavigation { get; set; }

    public virtual SanPham MaSanPhamNavigation { get; set; }
}