// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class DanhMuc
{
    public int MaDanhMuc { get; set; }

    public string TenDanhMuc { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<SanPham> SanPham { get; set; } = new List<SanPham>();
}