// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class NguoiDung
{
    public int MaNguoiDung { get; set; }

    public string TenDangNhap { get; set; }

    public string MatKhau { get; set; }

    public string HoTen { get; set; }

    public string Email { get; set; }

    public int MaVaiTro { get; set; }

    public bool IsDeleted { get; set; }

    public virtual VaiTro MaVaiTroNavigation { get; set; }

    public virtual ICollection<PhieuNhap> PhieuNhap { get; set; } = new List<PhieuNhap>();

    public virtual ICollection<PhieuXuat> PhieuXuat { get; set; } = new List<PhieuXuat>();
}