// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class NhaCungCap
{
    public int MaNhaCungCap { get; set; }

    public string TenNhaCungCap { get; set; }

    public string SoDienThoai { get; set; }

    public string DiaChi { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<PhieuNhap> PhieuNhap { get; set; } = new List<PhieuNhap>();
}