// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class PhieuNhap
{
    public int MaPhieuNhap { get; set; }

    public DateTime NgayNhap { get; set; }

    public decimal TongTien { get; set; }

    public string GhiChu { get; set; }

    public int MaNhaCungCap { get; set; }

    public int MaNguoiDung { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhap { get; set; } = new List<ChiTietPhieuNhap>();

    public virtual NguoiDung MaNguoiDungNavigation { get; set; }

    public virtual NhaCungCap MaNhaCungCapNavigation { get; set; }

    public virtual ICollection<SeriSanPham> SeriSanPham { get; set; } = new List<SeriSanPham>();
}