// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class PhieuXuat
{
    public int MaPhieuXuat { get; set; }

    public DateTime NgayXuat { get; set; }

    public string TenKhachHang { get; set; }

    public string SoDienThoaiKhach { get; set; }

    public decimal TongTien { get; set; }

    public int MaNguoiDung { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuat { get; set; } = new List<ChiTietPhieuXuat>();

    public virtual NguoiDung MaNguoiDungNavigation { get; set; }

    public virtual ICollection<SeriSanPham> SeriSanPham { get; set; } = new List<SeriSanPham>();
}