// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QuanLyKhoLinhKienPC.Models;

public partial class QuanLyKhoLinhKienPCContext : DbContext
{
    public QuanLyKhoLinhKienPCContext(DbContextOptions<QuanLyKhoLinhKienPCContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChiTietPhieuNhap> ChiTietPhieuNhap { get; set; }

    public virtual DbSet<ChiTietPhieuXuat> ChiTietPhieuXuat { get; set; }

    public virtual DbSet<DanhMuc> DanhMuc { get; set; }

    public virtual DbSet<NguoiDung> NguoiDung { get; set; }

    public virtual DbSet<NhaCungCap> NhaCungCap { get; set; }

    public virtual DbSet<PhieuNhap> PhieuNhap { get; set; }

    public virtual DbSet<PhieuXuat> PhieuXuat { get; set; }

    public virtual DbSet<SanPham> SanPham { get; set; }

    public virtual DbSet<SeriSanPham> SeriSanPham { get; set; }

    public virtual DbSet<VaiTro> VaiTro { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChiTietPhieuNhap>(entity =>
        {
            entity.HasKey(e => e.MaChiTietNhap).HasName("PK__ChiTietP__D10F254CF0081842");

            entity.Property(e => e.DonGiaNhap).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.MaPhieuNhapNavigation).WithMany(p => p.ChiTietPhieuNhap)
                .HasForeignKey(d => d.MaPhieuNhap)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChiTietNhap_PhieuNhap");

            entity.HasOne(d => d.MaSanPhamNavigation).WithMany(p => p.ChiTietPhieuNhap)
                .HasForeignKey(d => d.MaSanPham)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChiTietNhap_SanPham");
        });

        modelBuilder.Entity<ChiTietPhieuXuat>(entity =>
        {
            entity.HasKey(e => e.MaChiTietXuat).HasName("PK__ChiTietP__C10F0DECED5BEC7C");

            entity.Property(e => e.GiaTien).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.MaPhieuXuatNavigation).WithMany(p => p.ChiTietPhieuXuat)
                .HasForeignKey(d => d.MaPhieuXuat)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChiTietXuat_PhieuXuat");

            entity.HasOne(d => d.MaSeriNavigation).WithMany(p => p.ChiTietPhieuXuat)
                .HasForeignKey(d => d.MaSeri)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChiTietXuat_Seri");
        });

        modelBuilder.Entity<DanhMuc>(entity =>
        {
            entity.HasKey(e => e.MaDanhMuc).HasName("PK__DanhMuc__B375088741C16EB1");

            entity.Property(e => e.TenDanhMuc)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<NguoiDung>(entity =>
        {
            entity.HasKey(e => e.MaNguoiDung).HasName("PK__NguoiDun__C539D762E93F81DC");

            entity.HasIndex(e => e.TenDangNhap, "UQ__NguoiDun__55F68FC0679A3F1F").IsUnique();

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.HoTen).HasMaxLength(100);
            entity.Property(e => e.MatKhau)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.TenDangNhap)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.MaVaiTroNavigation).WithMany(p => p.NguoiDung)
                .HasForeignKey(d => d.MaVaiTro)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_NguoiDung_VaiTro");
        });

        modelBuilder.Entity<NhaCungCap>(entity =>
        {
            entity.HasKey(e => e.MaNhaCungCap).HasName("PK__NhaCungC__53DA92057C0299C4");

            entity.Property(e => e.SoDienThoai)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TenNhaCungCap)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<PhieuNhap>(entity =>
        {
            entity.HasKey(e => e.MaPhieuNhap).HasName("PK__PhieuNha__1470EF3BC544D210");

            entity.Property(e => e.NgayNhap)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TongTien).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.PhieuNhap)
                .HasForeignKey(d => d.MaNguoiDung)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhieuNhap_NguoiDung");

            entity.HasOne(d => d.MaNhaCungCapNavigation).WithMany(p => p.PhieuNhap)
                .HasForeignKey(d => d.MaNhaCungCap)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhieuNhap_NhaCungCap");
        });

        modelBuilder.Entity<PhieuXuat>(entity =>
        {
            entity.HasKey(e => e.MaPhieuXuat).HasName("PK__PhieuXua__26C4B5A2DB64D8AB");

            entity.Property(e => e.NgayXuat)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.SoDienThoaiKhach)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.TenKhachHang).HasMaxLength(100);
            entity.Property(e => e.TongTien).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.MaNguoiDungNavigation).WithMany(p => p.PhieuXuat)
                .HasForeignKey(d => d.MaNguoiDung)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhieuXuat_NguoiDung");
        });

        modelBuilder.Entity<SanPham>(entity =>
        {
            entity.HasKey(e => e.MaSanPham).HasName("PK__SanPham__FAC7442D50E4102B");

            entity.Property(e => e.GiaBan).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TenSanPham)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.ThoiGianBaoHanh).HasDefaultValue(12);

            entity.HasOne(d => d.MaDanhMucNavigation).WithMany(p => p.SanPham)
                .HasForeignKey(d => d.MaDanhMuc)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SanPham_DanhMuc");
        });

        modelBuilder.Entity<SeriSanPham>(entity =>
        {
            entity.HasKey(e => e.MaSeri).HasName("PK__SeriSanP__B3BADCB55CA1562E");

            entity.HasIndex(e => e.SoSeri, "UQ_SeriSanPham_SoSeri").IsUnique();

            entity.Property(e => e.SoSeri)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TrangThai).HasDefaultValue(1);

            entity.HasOne(d => d.MaPhieuNhapNavigation).WithMany(p => p.SeriSanPham)
                .HasForeignKey(d => d.MaPhieuNhap)
                .HasConstraintName("FK_SeriSanPham_PhieuNhap");

            entity.HasOne(d => d.MaPhieuXuatNavigation).WithMany(p => p.SeriSanPham)
                .HasForeignKey(d => d.MaPhieuXuat)
                .HasConstraintName("FK_SeriSanPham_PhieuXuat");

            entity.HasOne(d => d.MaSanPhamNavigation).WithMany(p => p.SeriSanPham)
                .HasForeignKey(d => d.MaSanPham)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_SeriSanPham_SanPham");
        });

        modelBuilder.Entity<VaiTro>(entity =>
        {
            entity.HasKey(e => e.MaVaiTro).HasName("PK__VaiTro__C24C41CF54B870B4");

            entity.Property(e => e.TenVaiTro)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}