// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class SanPham
{
    public int MaSanPham { get; set; }

    public string TenSanPham { get; set; }

    public string HinhAnh { get; set; }

    public decimal GiaBan { get; set; }

    public string ThongSoKyThuat { get; set; }

    public int ThoiGianBaoHanh { get; set; }

    public int MaDanhMuc { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhap { get; set; } = new List<ChiTietPhieuNhap>();

    public virtual DanhMuc MaDanhMucNavigation { get; set; }

    public virtual ICollection<SeriSanPham> SeriSanPham { get; set; } = new List<SeriSanPham>();
}