// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class SeriSanPham
{
    public int MaSeri { get; set; }

    public string SoSeri { get; set; }

    public int TrangThai { get; set; }

    public int MaSanPham { get; set; }

    public int? MaPhieuNhap { get; set; }

    public int? MaPhieuXuat { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuat { get; set; } = new List<ChiTietPhieuXuat>();

    public virtual PhieuNhap MaPhieuNhapNavigation { get; set; }

    public virtual PhieuXuat MaPhieuXuatNavigation { get; set; }

    public virtual SanPham MaSanPhamNavigation { get; set; }
}