// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKhoLinhKienPC.Models;

public partial class VaiTro
{
    public int MaVaiTro { get; set; }

    public string TenVaiTro { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<NguoiDung> NguoiDung { get; set; } = new List<NguoiDung>();
}